import {
  BellRing,
  ChartColumn,
  Cloud,
  Code2,
  Gamepad2,
  Globe,
  HousePlus,
  IndianRupee,
  KeyRound,
  LayoutDashboard,
  Palette,
  PenTool,
  Plug,
  RefreshCw,
  Repeat,
  Rocket,
  Search,
  Send,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  TabletSmartphone,
  TicketPercent,
  Zap,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  smartphone: Smartphone,
  "gamepad-2": Gamepad2,
  globe: Globe,
  palette: Palette,
  "shield-check": ShieldCheck,
  cloud: Cloud,
  search: Search,
  "pen-tool": PenTool,
  "code-2": Code2,
  rocket: Rocket,
  "key-round": KeyRound,
  "ticket-percent": TicketPercent,
  "layout-dashboard": LayoutDashboard,
  "tablet-smartphone": TabletSmartphone,
  "bell-ring": BellRing,
  zap: Zap,
  "indian-rupee": IndianRupee,
  "chart-column": ChartColumn,
  plug: Plug,
  "shopping-cart": ShoppingCart,
  "refresh-cw": RefreshCw,
  "house-plus": HousePlus,
  send: Send,
  repeat: Repeat,
};

export function getIcon(name?: string): LucideIcon {
  return (name && iconMap[name]) || Sparkles;
}
